# Generated by Django 5.1.3 on 2024-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
